version: "3"
services:
  my_jupyter:
    build: ./docker/jupyter/
    volumes:
      - .:/home/jovyan/work
    ports:
      - 8888:8888
  my_postgres:
    image: postgres:10-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
volumes:
  postgres_data:
